config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  resources :phone_calls
  root to: "phone_calls#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/phone_call.rb
class PhoneCall < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  http_basic_authenticate_with name: ENV["BASIC_AUTH_USERNAME"], password: ENV["BASIC_AUTH_PASSWORD"]
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/phone_calls_controller.rb
class PhoneCallsController < ApplicationController
  before_action :set_phone_call, only: [:show]
  def index
    @phone_calls = PhoneCall.all
  end

  def show
  end

  def new
    @phone_call = PhoneCall.new
  end

  def create
    @phone_call = PhoneCall.new(phone_call_params)
    @phone_call.save
    flash.notice = "Phone Call from '#{@phone_call.caller}' Logged!"
    redirect_to phone_call_path(@phone_call)
  end

  private

  def set_phone_call
    @phone_call = PhoneCall.find(params[:id])
  end

  def phone_call_params
    params.require(:phone_call).permit(:caller, :start_time, :end_time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phone_calls_helper.rb
module PhoneCallsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Toxicology Tracker" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/phone_calls/_form.html.erb
<%= form_for(@phone_call) do |f|%>
<ul>
    <% @phone_call.errors.full_messages.each do |error| %>
    <li><%= error %></li>
    <% end %>
</ul>
<p>
    <%= f.label :caller %><br />
    <%= f.text_field :caller %>
</p>
<p>
    <%= f.label :start_time %><br />
    <%= f.datetime_local_field :start_time %>
</p>
<p>
  <%= f.label :end_time %><br />
  <%= f.datetime_local_field :end_time %>
</p>
<p>
    <%= f.submit%>
</p>
<% end %>

app/views/phone_calls/index.html.erb
<h1>All Phone Calls</h1>

<ul id="phone_calls">
    <% @phone_calls.each do |phone_call|%>
    <li>
        <%= link_to phone_call.caller, phone_call_path(phone_call) %>
    </li>
    <% end %>
</ul>

<%= link_to "Log Phone Call", new_phone_call_path %>

app/views/phone_calls/new.html.erb
<h1>Log New Phone Call</h1>
<%= render partial: 'form' %>

app/views/phone_calls/show.html.erb
<h1><%= @phone_call.caller %></h1>
<p><%= @phone_call.start_time %></p>
<p><%= @phone_call.end_time %></p>
<%= link_to "<< Back to List", phone_calls_path %>